CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    email VARCHAR(255)
);

CREATE TABLE questionnaire (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    owner_id BIGINT REFERENCES "user"(id)
);

CREATE TABLE question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(255)
);

CREATE TABLE questionnaire_editors (
    questionnaire_id BIGINT REFERENCES questionnaire(id),
    editor_id BIGINT REFERENCES "user"(id),
    PRIMARY KEY (questionnaire_id, editor_id)
);

CREATE TABLE questionnaire_questions (
    questionnaire_id BIGINT REFERENCES questionnaire(id),
    question_id BIGINT REFERENCES question(id),
    PRIMARY KEY (questionnaire_id, question_id)
);